In [13]:
import pandas as pd
import os

In [14]:
df=pd.read_csv("CLHLS_14_withBiomarkers.csv", encoding='latin1')
df

C:\Users\17544\AppData\Local\Temp\ipykernel_99236\755027401.py:1: DtypeWarning: Columns (115,164,167,358,390,441,452,505,508,902,908,922,927,931,936,940,945,949,954,956,958,963,967,972,976,981,990,999,1012,1014,1040,1058,1061,1073,1098) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv("CLHLS_14_withBiomarkers.csv", encoding='latin1',na_values=[' ','-1','8','9'])

,ID,YEARIN,MONTHIN,DAYIN,V_BTHYR,V_BTHMON,TYPE,PROV,RESIDENC,TRUEAGE,...,RBC,HGB,HCT,MCV,MCH,MCHC,PLT,MPV,PDW,PCT
0,11000308,2014,5.0,14.0,1918,NaN,5,11,1,95,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,11001208,2014,5.0,27.0,1915,6.0,5,11,1,98,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,11002308,2014,5.0,20.0,1922,NaN,5,11,1,91,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,11002508,2014,4.0,24.0,1906,12.0,5,11,1,107,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,11002908,2014,4.0,28.0,1943,6.0,5,11,2,70,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7187,61163005,2014,5.0,22.0,1938,10.0,4,61,3,75,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7188,61163405,2014,5.0,27.0,1938,NaN,4,61,2,75,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7189,61163505,2014,5.0,28.0,1938,3.0,4,61,3,76,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7190,61163805,2014,5.0,13.0,1940,2.0,4,61,1,74,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7191,61164005,2014,5.0,21.0,1938,12.0,4,61,2,75,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
unrefined=pd.read_excel("labeledData_unrefined.xlsx")
unrefined

,Variable,Description,Label_byOrgan,PotentialLabel_byOrgan,ValidSize
0,ID,id，省份代码+编号+第一波采访年份,NotUseful,NaN,7192.0
1,YEARIN,2014 年采访年,NotUseful,NaN,7192.0
2,MONTHIN,2014 年采访月份,NotUseful,NaN,7192.0
3,DAYIN,2014 年采访日,NotUseful,NaN,7192.0
4,V_BTHYR,已核实的出生年份,NotUseful,NaN,7192.0
...,...,...,...,...,...
704,MCHC,平均红细胞血红蛋白浓度,NaN,NaN,2546.0
705,PLT,血小板计数,NaN,NaN,2546.0
706,MPV,平均血小板体积,NaN,NaN,2546.0
707,PDW,血小板体积分布宽度,NaN,NaN,2546.0
708,PCT,血小板压积,NaN,NaN,2546.0

In [16]:
# 计算每一列的有效值数量
valid_size = df.notna().sum()

# 将有效值数量填入unrefined的ValidSize列
unrefined['ValidSize'] = unrefined['Variable'].apply(lambda x: valid_size[x] if x in valid_size else None)

unrefined

,Variable,Description,Label_byOrgan,PotentialLabel_byOrgan,ValidSize
0,ID,id，省份代码+编号+第一波采访年份,NotUseful,NaN,7192.0
1,YEARIN,2014 年采访年,NotUseful,NaN,7192.0
2,MONTHIN,2014 年采访月份,NotUseful,NaN,6111.0
3,DAYIN,2014 年采访日,NotUseful,NaN,6821.0
4,V_BTHYR,已核实的出生年份,NotUseful,NaN,7192.0
...,...,...,...,...,...
704,MCHC,平均红细胞血红蛋白浓度,NaN,NaN,2497.0
705,PLT,血小板计数,NaN,NaN,2496.0
706,MPV,平均血小板体积,NaN,NaN,2389.0
707,PDW,血小板体积分布宽度,NaN,NaN,2482.0
708,PCT,血小板压积,NaN,NaN,1711.0

In [17]:
unrefined.to_excel("labeledData_unrefined.xlsx", index=False)